// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJXYL5WumQQ46K7vxn3CazP1-noHqm8w',
    appId: '1:740548224202:web:2c32dfef7374f0f74e0033',
    messagingSenderId: '740548224202',
    projectId: 'todyapp-notes',
    authDomain: 'todyapp-notes.firebaseapp.com',
    storageBucket: 'todyapp-notes.firebasestorage.app',
    measurementId: 'G-F3LEDNG65J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3DaduvkIXpzFGKwpWFnVsPNOVhS0_pg',
    appId: '1:740548224202:android:08d68731afd0f1064e0033',
    messagingSenderId: '740548224202',
    projectId: 'todyapp-notes',
    storageBucket: 'todyapp-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDix3D1zU0pKODpkNjrhOaOPCWjvP6f_jw',
    appId: '1:740548224202:ios:47e7299e09c44ecb4e0033',
    messagingSenderId: '740548224202',
    projectId: 'todyapp-notes',
    storageBucket: 'todyapp-notes.firebasestorage.app',
    iosBundleId: 'com.example.todyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDix3D1zU0pKODpkNjrhOaOPCWjvP6f_jw',
    appId: '1:740548224202:ios:47e7299e09c44ecb4e0033',
    messagingSenderId: '740548224202',
    projectId: 'todyapp-notes',
    storageBucket: 'todyapp-notes.firebasestorage.app',
    iosBundleId: 'com.example.todyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbJXYL5WumQQ46K7vxn3CazP1-noHqm8w',
    appId: '1:740548224202:web:36b49359af96517f4e0033',
    messagingSenderId: '740548224202',
    projectId: 'todyapp-notes',
    authDomain: 'todyapp-notes.firebaseapp.com',
    storageBucket: 'todyapp-notes.firebasestorage.app',
    measurementId: 'G-RR18CGVD0Y',
  );

}